services:
  builderius_layout.layout_content_1:
    class: 'Builderius\Bundle\LayoutBundle\Model\BuilderiusLayout'
    arguments:
      - name: 'layout_content_1'
        label: 'Content #1'
        technologies: ['html']
        category: 'content_sections'
        image: 'https://showcase.builderius.io/wp-content/uploads/2023/02/layout_content_1.jpg'
        tags:
          - 'dark'
        config:
          ---
          modules:
            u443477ad:
              id: u443477ad
              name: GenericBlock
              label: 'content #1'
              settings:
                - name: padding
                  value:
                    all:
                      original:
                        a3: 40
                        b3: px
                        a1: 40
                        b1: px
                - name: backgroundColor
                  value:
                    all:
                      original:
                        v1:
                          - '--bgcolor'
                        a1: 'rgba(15, 26, 38, 1.00)'
                - name: width
                  value:
                    all:
                      original:
                        a1: 100
                        b1: '%'
                - name: justifyContent
                  value:
                    all:
                      original:
                        a1: center
                - name: alignItems
                  value:
                    all:
                      original:
                        a1: center
                - name: flexDirection
                  value:
                    all:
                      original:
                        a1: column
                - name: display
                  value:
                    all:
                      original:
                        a1: flex
                - name: htmlTagContainer
                  value:
                    a1: div
                - name: isLinkWrapper
                  value:
                    a1: false
              parent: ''
            u7fd7fb45:
              id: u7fd7fb45
              name: GenericBlock
              label: inner
              settings:
                - name: alignItems
                  value:
                    all:
                      original:
                        a1: center
                - name: flexDirection
                  value:
                    all:
                      original:
                        a1: column
                - name: display
                  value:
                    all:
                      original:
                        a1: flex
                - name: padding
                  value:
                    all:
                      original:
                        a4: 20
                        b4: px
                        a2: 20
                        b2: px
                - name: margin
                  value:
                    all:
                      original:
                        b4: auto
                        b2: auto
                - name: maxWidth
                  value:
                    all:
                      original:
                        b1: px
                        a1: 900
                - name: htmlTagContainer
                  value:
                    a1: div
                - name: isLinkWrapper
                  value:
                    a1: false
              parent: u443477ad
              index: 0
            u650826a7:
              id: u650826a7
              name: Anchor
              label: CTA
              settings:
                - name: backgroundColor
                  value:
                    all:
                      ':hover':
                        v1:
                          - '--accentcolor'
                        a1: 'rgba(252, 54, 59, 1.00)'
                - name: cursor
                  value:
                    all:
                      ':hover':
                        a1: pointer
                - name: padding
                  value:
                    all:
                      original:
                        a4: 20
                        a3: 10
                        b4: px
                        a2: 20
                        b3: px
                        a1: 10
                        b2: px
                        b1: px
                - name: borderRadius
                  value:
                    all:
                      original:
                        a4: 25
                        a3: 25
                        b4: px
                        a2: 25
                        b3: px
                        a1: 25
                        b2: px
                        b1: px
                - name: border
                  value:
                    all:
                      original:
                        d1: 'rgba(252, 54, 59, 1.00)'
                        c1: solid
                        d2: 'rgba(252, 54, 59, 1.00)'
                        b1: px
                        c2: solid
                        d3: 'rgba(252, 54, 59, 1.00)'
                        b2: px
                        c3: solid
                        d4: 'rgba(252, 54, 59, 1.00)'
                        a1: 1
                        b3: px
                        c4: solid
                        a2: 1
                        b4: px
                        a3: 1
                        a4: 1
                        v1:
                          - '--accentborder'
                        v2:
                          - '--accentborder'
                        v3:
                          - '--accentborder'
                        v4:
                          - '--accentborder'
                - name: color
                  value:
                    all:
                      original:
                        v1:
                          - '--accentcolor'
                        a1: 'rgba(252, 54, 59, 1.00)'
                      ':hover':
                        v1:
                          - '--textcolor'
                        a1: 'rgba(255, 255, 255, 1.00)'
                - name: textTransform
                  value:
                    all:
                      original:
                        a1: uppercase
                - name: textDecoration
                  value:
                    all:
                      original:
                        a1: none
                - name: font
                  value:
                    all:
                      original:
                        a1: google
                        b1: sans-serif
                        c1: Karla
                        a2: normal
                        a3: '700'
                      ' span':
                        a3: '400'
                    '(max-width: 800px)':
                      original:
                        a5: 14
                        b5: px
                - name: dataAnchor
                  value:
                    a1: Load more
              parent: u7fd7fb45
              index: 3
            u7a9d234b:
              id: u7a9d234b
              name: Paragraph
              label: subtitle
              settings:
                - name: textAlign
                  value:
                    '(max-width: 600px)':
                      original:
                        a1: center
                    all:
                      original:
                        a1: center
                - name: margin
                  value:
                    all:
                      original:
                        a3: 60
                        b3: px
                - name: color
                  value:
                    all:
                      original:
                        v1:
                          - '--textcolor-alt'
                        a1: 'rgba(191, 206, 217, 1.00)'
                - name: font
                  value:
                    all:
                      original:
                        a5: 24
                        b5: px
                        a2: normal
                        a1: google
                        b1: sans-serif
                        c1: Karla
                    '(max-width: 800px)':
                      original:
                        a5: 19
                        b5: px
                - name: dataParagraph
                  value:
                    a1: 'Articles from our blog. Interesting interviews, expert reviews.'
              parent: u7fd7fb45
              index: 1
            ud006ed77:
              id: ud006ed77
              name: Heading
              label: Heading H2
              settings:
                - name: textAlign
                  value:
                    '(max-width: 600px)':
                      original:
                        a1: center
                - name: margin
                  value:
                    all:
                      original:
                        a3: 15
                        b3: px
                - name: font
                  value:
                    all:
                      original:
                        a6: 48
                        a5: 40
                        b6: px
                        b5: px
                        a2: normal
                        a1: google
                        b1: serif
                        c1: Spectral
                    '(max-width: 800px)':
                      original:
                        a6: 40
                        a5: 34
                        b6: px
                        b5: px
                - name: color
                  value:
                    all:
                      original:
                        v1:
                          - '--textcolor'
                        a1: 'rgba(255, 255, 255, 1.00)'
                - name: htmlTagHeading
                  value:
                    a1: h2
                - name: dataHeading
                  value:
                    a1: Blog
              parent: u7fd7fb45
              index: 0
            u32d99010:
              id: u32d99010
              name: Collection
              label: post items
              settings:
                - name: justifyContent
                  value:
                    all:
                      original:
                        a1: center
                - name: flexWrap
                  value:
                    all:
                      original:
                        a1: wrap
                - name: margin
                  value:
                    all:
                      original:
                        a3: 40
                        b3: px
                - name: gap
                  value:
                    all:
                      original:
                        b1: px
                        a1: 20
                - name: display
                  value:
                    all:
                      original:
                        a1: flex
                - name: htmlAttribute
                  value:
                    i1:
                      - a1: data-content
                        b1: >-
                          [{"imgUrl":"https://source.unsplash.com/3OiYMgDKJ6k/900x900","title":"Beautiful
                          layouts","date":"2021-09-01"},{"imgUrl":"https://source.unsplash.com/3OiYMgDKJ6k/900x900","title":"Beautiful
                          layouts","date":"2021-09-01"},{"imgUrl":"https://source.unsplash.com/3OiYMgDKJ6k/900x900","title":"Beautiful
                          layouts","date":"2021-09-01"}]
              parent: u7fd7fb45
              index: 2
            ua1b636d0:
              id: ua1b636d0
              name: Template
              label: Template
              settings: [ ]
              parent: u32d99010
              index: 0
            ua6b20ef8:
              id: ua6b20ef8
              name: GenericBlock
              label: item
              settings:
                - name: width
                  value:
                    all:
                      original:
                        b1: px
                        a1: 200
                - name: flexDirection
                  value:
                    all:
                      original:
                        a1: column
                - name: display
                  value:
                    all:
                      original:
                        a1: flex
                - name: htmlTagContainer
                  value:
                    a1: div
                - name: isLinkWrapper
                  value:
                    a1: false
              parent: ua1b636d0
              index: 0
            u8af23132:
              id: u8af23132
              name: GenericBlock
              label: picture
              settings:
                - name: margin
                  value:
                    all:
                      original:
                        a3: 15
                        b3: px
                - name: height
                  value:
                    all:
                      original:
                        b1: px
                        a1: 320
                - name: width
                  value:
                    all:
                      original:
                        a1: 100
                        b1: '%'
                - name: display
                  value:
                    all:
                      original:
                        a1: flex
                - name: htmlTagContainer
                  value:
                    a1: picture
                - name: isLinkWrapper
                  value:
                    a1: false
              parent: ua6b20ef8
              index: 0
            u619729d6:
              id: u619729d6
              name: Source
              label: Source
              settings:
                - name: display
                  value:
                    all:
                      original:
                        a1: none
                - name: src
                  value:
                    a1: '{{imgUrl}}'
              parent: u8af23132
              index: 0
            u6ed61e94:
              id: u6ed61e94
              name: Image
              label: Image
              settings:
                - name: objectFit
                  value:
                    all:
                      original:
                        a1: cover
                - name: height
                  value:
                    all:
                      original:
                        a1: 100
                        b1: '%'
                - name: width
                  value:
                    all:
                      original:
                        a1: 100
                        b1: '%'
              parent: u8af23132
              index: 1
            udfb07eef:
              id: udfb07eef
              name: Heading
              label: post title
              settings:
                - name: margin
                  value:
                    all:
                      original:
                        a3: 10
                        b3: px
                - name: color
                  value:
                    all:
                      original:
                        v1:
                          - '--accentcolor'
                        a1: 'rgba(252, 54, 59, 1.00)'
                - name: font
                  value:
                    all:
                      original:
                        a5: 18
                        b5: px
                        a3: '700'
                        a2: normal
                        a1: google
                        b1: sans-serif
                        c1: Karla
                - name: htmlTagHeading
                  value:
                    a1: h3
                - name: dataHeading
                  value:
                    a1: '{{title}}'
              parent: ua6b20ef8
              index: 1
            u2644ebff:
              id: u2644ebff
              name: Time
              label: post time
              settings:
                - name: color
                  value:
                    all:
                      original:
                        v1:
                          - '--textcolor-alt'
                        a1: 'rgba(191, 206, 217, 1.00)'
                - name: font
                  value:
                    all:
                      original:
                        a5: 14
                        b5: px
                        a2: normal
                        a1: google
                        b1: sans-serif
                        c1: Karla
                - name: dataTime
                  value:
                    a1: '{{date}}'
                - name: dateTimeFormat
                  value:
                    a1:
                      - d
                      - /
                      - m
                      - /
                      - 'Y'
              parent: ua6b20ef8
              index: 2
          indexes:
            root:
              - u443477ad
            u443477ad:
              - u7fd7fb45
            u7fd7fb45:
              - ud006ed77
              - u650826a7
              - u32d99010
              - u7a9d234b
            u32d99010:
              - ua1b636d0
            ua1b636d0:
              - ua6b20ef8
            ua6b20ef8:
              - u8af23132
              - udfb07eef
              - u2644ebff
            u8af23132:
              - u619729d6
              - u6ed61e94
          version:
            builderius: 0.9.6
    tags:
      - { name: builderius_layout }
