services:
  builderius_layout.layout_content_7:
    class: 'Builderius\Bundle\LayoutBundle\Model\BuilderiusLayout'
    arguments:
      - name: 'layout_content_7'
        label: 'Content #7'
        technologies: ['html']
        category: 'content_sections'
        image: 'https://showcase.builderius.io/wp-content/uploads/2023/02/layout_content_7.png'
        tags:
          - 'dark'
        config:
          ---
          modules:
            ubffb388d:
              id: ubffb388d
              name: GenericBlock
              label: 'content #7'
              settings:
                - name: padding
                  value:
                    '(max-width: 600px)':
                      original:
                        a3: 50
                        b3: px
                        a1: 50
                        b1: px
                    all:
                      original:
                        a3: 50
                        b3: px
                        a1: 60
                        b1: px
                - name: backgroundColor
                  value:
                    all:
                      original:
                        v1:
                          - '--bgcolor'
                        a1: 'rgba(15, 26, 38, 1.00)'
                - name: height
                  value:
                    '(max-width: 600px)':
                      original:
                        b1: auto
                - name: width
                  value:
                    all:
                      original:
                        a1: 100
                        b1: '%'
                - name: justifyContent
                  value:
                    all:
                      original:
                        a1: center
                - name: alignItems
                  value:
                    all:
                      original:
                        a1: center
                - name: flexDirection
                  value:
                    all:
                      original:
                        a1: column
                - name: display
                  value:
                    all:
                      original:
                        a1: flex
                - name: htmlTagContainer
                  value:
                    a1: div
                - name: isLinkWrapper
                  value:
                    a1: false
              parent: ''
            ue40cbdbc:
              id: ue40cbdbc
              name: GenericBlock
              label: headerInner
              settings:
                - name: textAlign
                  value:
                    '(max-width: 800px)':
                      original:
                        a1: center
                - name: flexDirection
                  value:
                    '(max-width: 800px)':
                      original:
                        a1: column
                - name: flexWrap
                  value:
                    '(max-width: 800px)':
                      original:
                        a1: wrap
                - name: padding
                  value:
                    all:
                      original:
                        a4: 50
                        b4: px
                        a2: 50
                        b2: px
                - name: maxWidth
                  value:
                    all:
                      original:
                        b1: px
                        a1: 1440
                - name: height
                  value:
                    '(max-width: 800px)':
                      original:
                        b1: auto
                - name: width
                  value:
                    all:
                      original:
                        a1: 100
                        b1: '%'
                - name: boxSizing
                  value:
                    all:
                      original:
                        a1: border-box
                - name: alignItems
                  value:
                    all:
                      original:
                        a1: center
                - name: justifyContent
                  value:
                    all:
                      original:
                        a1: space-between
                - name: display
                  value:
                    all:
                      original:
                        a1: flex
                      ' #hamburger-input3:checked + nav':
                        a1: flex
                - name: htmlTagContainer
                  value:
                    a1: div
                - name: isLinkWrapper
                  value:
                    a1: false
              parent: ubffb388d
              index: 0
            u0ca9b661:
              id: u0ca9b661
              name: Heading
              label: Heading H2
              settings:
                - name: width
                  value:
                    all:
                      original:
                        a1: 50
                        b1: '%'
                - name: textAlign
                  value:
                    '(max-width: 600px)':
                      original:
                        a1: center
                - name: margin
                  value:
                    all:
                      original:
                        a3: 15
                        b3: px
                - name: font
                  value:
                    all:
                      original:
                        a6: 48
                        a5: 40
                        b6: px
                        b5: px
                        a2: normal
                        a1: google
                        b1: serif
                        c1: Spectral
                    '(max-width: 800px)':
                      original:
                        a6: 40
                        a5: 34
                        b6: px
                        b5: px
                - name: color
                  value:
                    all:
                      original:
                        v1:
                          - '--textcolor'
                        a1: 'rgba(255, 255, 255, 1.00)'
                - name: htmlTagHeading
                  value:
                    a1: h2
                - name: dataHeading
                  value:
                    a1: >-
                      <strong class="font-weight-extra-bold">Layout</strong> Styles &amp;
                      Variants
              parent: ue40cbdbc
              index: 0
            u47f0cc83:
              id: u47f0cc83
              name: Paragraph
              label: subtitle
              settings:
                - name: width
                  value:
                    all:
                      original:
                        a1: 50
                        b1: '%'
                - name: textAlign
                  value:
                    '(max-width: 600px)':
                      original:
                        a1: center
                - name: margin
                  value:
                    all:
                      original:
                        a3: 30
                        b3: px
                - name: color
                  value:
                    all:
                      original:
                        v1:
                          - '--textcolor-alt'
                        a1: 'rgba(191, 206, 217, 1.00)'
                - name: font
                  value:
                    all:
                      original:
                        a5: 24
                        b5: px
                        a2: normal
                        a1: google
                        b1: sans-serif
                        c1: Karla
                    '(max-width: 800px)':
                      original:
                        a5: 19
                        b5: px
                - name: dataParagraph
                  value:
                    a1: >-
                      Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam
                      nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat
                      volutpat.
              parent: ue40cbdbc
              index: 1
          indexes:
            root:
              - ubffb388d
            ubffb388d:
              - ue40cbdbc
            ue40cbdbc:
              - u0ca9b661
              - u47f0cc83
          version:
            builderius: 0.9.6
    tags:
      - { name: builderius_layout }