services:
  builderius_template.template_acceptable_hook.generate_before_header:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_before_header
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_header:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_header
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_inside_navigation:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_inside_navigation
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_header:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_header
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_credits:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_credits
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_before_content:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_before_content
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_before_main_content:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_before_main_content
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_content:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_content
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_entry_content:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_entry_content
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_entry_title:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_entry_title
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_inside_mobile_header:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_inside_mobile_header
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_inside_container:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_inside_container
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_sidebars:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_sidebars
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_entry_header:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_entry_header
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_paging_navigation:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_paging_navigation
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_before_header_content:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_before_header_content
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_main_content:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_main_content
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_inside_slideout_navigation:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_inside_slideout_navigation
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_before_footer:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_before_footer
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_inside_mobile_menu_bar:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_inside_mobile_menu_bar
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_archive_title:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_archive_title
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_header_content:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_header_content
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_inside_secondary_navigation:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_inside_secondary_navigation
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_before_copyright:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_before_copyright
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_before_footer_content:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_before_footer_content
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_inside_mobile_menu:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_inside_mobile_menu
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_footer_content:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_footer_content
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_footer_widgets:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_footer_widgets
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_primary_content_area:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_primary_content_area
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_archive_title:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_archive_title
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_archive_description:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_archive_description
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_before_right_sidebar_content:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_before_right_sidebar_content
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_before_comments:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_before_comments
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_before_archive_title:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_before_archive_title
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_before_left_sidebar_content:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_before_left_sidebar_content
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_inside_mobile_header_menu:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_inside_mobile_header_menu
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_left_sidebar_content:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_left_sidebar_content
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_inside_comments:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_inside_comments
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_mobile_cart_items:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_mobile_cart_items
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_right_sidebar_content:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_right_sidebar_content
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_inside_secondary_mobile_menu:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_inside_secondary_mobile_menu
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_dashboard_after_header:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_dashboard_after_header
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_dashboard_inside_container:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_dashboard_inside_container
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_primary_menu:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_primary_menu
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_loop:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_loop
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_menu_bar_items:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_menu_bar_items
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_page_title:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_page_title
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_inside_site_container:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_inside_site_container
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_before_page_title:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_before_page_title
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_comment_text:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_comment_text
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_do_template_part:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_do_template_part
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_before_do_template_part:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_before_do_template_part
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_navigation:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_navigation
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_secondary_navigation:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_secondary_navigation
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_before_secondary_navigation:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_before_secondary_navigation
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_before_navigation:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_before_navigation
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }

  builderius_template.template_acceptable_hook.generate_after_mobile_menu_button:
    class: Builderius\Bundle\TemplateBundle\Model\BuilderiusTemplateAcceptableHook
    arguments:
      - name: generate_after_mobile_menu_button
    tags:
      - { name: builderius_template_acceptable_generatepress_hook }
