<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitfa5bbcaf1cdf95417437e5c717094074
{
    public static $files = array (
        '6e3fae29631ef280660b3cdad06f25a8' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php',
        '320cde22f66dd4f5d3fd621d3e88b98f' => __DIR__ . '/..' . '/symfony/polyfill-ctype/bootstrap.php',
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        '2df68f9e79c919e2d88506611769ed2e' => __DIR__ . '/..' . '/respect/stringifier/src/stringify.php',
        '8825ede83f2f289127722d4e842cf7e8' => __DIR__ . '/..' . '/symfony/polyfill-intl-grapheme/bootstrap.php',
        'e69f7f6ee287b969198c3c9d6777bd38' => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer/bootstrap.php',
        'b6b991a57620e2fb6b2f66f03fe9ddc2' => __DIR__ . '/..' . '/symfony/string/Resources/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'Builderius\\enshrined\\svgSanitize\\' => 33,
            'Builderius\\Zend\\EventManager\\' => 29,
            'Builderius\\Zend\\Code\\' => 21,
            'Builderius\\Twig\\' => 16,
            'Builderius\\Symfony\\Polyfill\\Mbstring\\' => 37,
            'Builderius\\Symfony\\Polyfill\\Intl\\Normalizer\\' => 44,
            'Builderius\\Symfony\\Polyfill\\Intl\\Grapheme\\' => 42,
            'Builderius\\Symfony\\Polyfill\\Ctype\\' => 34,
            'Builderius\\Symfony\\Contracts\\Translation\\' => 41,
            'Builderius\\Symfony\\Contracts\\Service\\' => 37,
            'Builderius\\Symfony\\Contracts\\EventDispatcher\\' => 45,
            'Builderius\\Symfony\\Contracts\\Cache\\' => 35,
            'Builderius\\Symfony\\Component\\Yaml\\' => 34,
            'Builderius\\Symfony\\Component\\VarExporter\\' => 41,
            'Builderius\\Symfony\\Component\\Templating\\' => 40,
            'Builderius\\Symfony\\Component\\String\\' => 36,
            'Builderius\\Symfony\\Component\\PropertyAccess\\' => 44,
            'Builderius\\Symfony\\Component\\Inflector\\' => 39,
            'Builderius\\Symfony\\Component\\Finder\\' => 36,
            'Builderius\\Symfony\\Component\\Filesystem\\' => 40,
            'Builderius\\Symfony\\Component\\ExpressionLanguage\\' => 48,
            'Builderius\\Symfony\\Component\\EventDispatcher\\' => 45,
            'Builderius\\Symfony\\Component\\DependencyInjection\\' => 49,
            'Builderius\\Symfony\\Component\\Config\\' => 36,
            'Builderius\\Symfony\\Component\\Cache\\' => 35,
            'Builderius\\Symfony\\Bridge\\Twig\\' => 31,
            'Builderius\\Symfony\\Bridge\\ProxyManager\\' => 39,
            'Builderius\\Sokil\\IsoCodes\\' => 26,
            'Builderius\\Respect\\Validation\\' => 30,
            'Builderius\\Respect\\Stringifier\\' => 31,
            'Builderius\\Psr\\Log\\' => 19,
            'Builderius\\Psr\\EventDispatcher\\' => 31,
            'Builderius\\Psr\\Container\\' => 25,
            'Builderius\\Psr\\Cache\\' => 21,
            'Builderius\\ProxyManager\\' => 24,
            'Builderius\\PackageVersions\\' => 27,
            'Builderius\\Mustache\\' => 20,
            'Builderius\\MooMoo\\Platform\\Bundle\\' => 34,
            'Builderius\\GraphQL\\' => 19,
            'Builderius\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Builderius\\enshrined\\svgSanitize\\' => 
        array (
            0 => __DIR__ . '/..' . '/enshrined/svg-sanitize/src',
        ),
        'Builderius\\Zend\\EventManager\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-eventmanager/src',
        ),
        'Builderius\\Zend\\Code\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-code/src',
        ),
        'Builderius\\Twig\\' => 
        array (
            0 => __DIR__ . '/..' . '/twig/twig/src',
        ),
        'Builderius\\Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Builderius\\Symfony\\Polyfill\\Intl\\Normalizer\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer',
        ),
        'Builderius\\Symfony\\Polyfill\\Intl\\Grapheme\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-intl-grapheme',
        ),
        'Builderius\\Symfony\\Polyfill\\Ctype\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-ctype',
        ),
        'Builderius\\Symfony\\Contracts\\Translation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/translation-contracts',
        ),
        'Builderius\\Symfony\\Contracts\\Service\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/service-contracts',
        ),
        'Builderius\\Symfony\\Contracts\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/event-dispatcher-contracts',
        ),
        'Builderius\\Symfony\\Contracts\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/cache-contracts',
        ),
        'Builderius\\Symfony\\Component\\Yaml\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/yaml',
        ),
        'Builderius\\Symfony\\Component\\VarExporter\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/var-exporter',
        ),
        'Builderius\\Symfony\\Component\\Templating\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/templating',
        ),
        'Builderius\\Symfony\\Component\\String\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/string',
        ),
        'Builderius\\Symfony\\Component\\PropertyAccess\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/property-access',
        ),
        'Builderius\\Symfony\\Component\\Inflector\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/inflector',
        ),
        'Builderius\\Symfony\\Component\\Finder\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/finder',
        ),
        'Builderius\\Symfony\\Component\\Filesystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/filesystem',
        ),
        'Builderius\\Symfony\\Component\\ExpressionLanguage\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/expression-language',
        ),
        'Builderius\\Symfony\\Component\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/event-dispatcher',
        ),
        'Builderius\\Symfony\\Component\\DependencyInjection\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/dependency-injection',
        ),
        'Builderius\\Symfony\\Component\\Config\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/config',
        ),
        'Builderius\\Symfony\\Component\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/cache',
        ),
        'Builderius\\Symfony\\Bridge\\Twig\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/twig-bridge',
        ),
        'Builderius\\Symfony\\Bridge\\ProxyManager\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/proxy-manager-bridge',
        ),
        'Builderius\\Sokil\\IsoCodes\\' => 
        array (
            0 => __DIR__ . '/..' . '/sokil/php-isocodes/src',
        ),
        'Builderius\\Respect\\Validation\\' => 
        array (
            0 => __DIR__ . '/..' . '/respect/validation/library',
        ),
        'Builderius\\Respect\\Stringifier\\' => 
        array (
            0 => __DIR__ . '/..' . '/respect/stringifier/src',
        ),
        'Builderius\\Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Builderius\\Psr\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/event-dispatcher/src',
        ),
        'Builderius\\Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'Builderius\\Psr\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'Builderius\\ProxyManager\\' => 
        array (
            0 => __DIR__ . '/..' . '/ocramius/proxy-manager/src/ProxyManager',
        ),
        'Builderius\\PackageVersions\\' => 
        array (
            0 => __DIR__ . '/..' . '/ocramius/package-versions/src/PackageVersions',
        ),
        'Builderius\\Mustache\\' => 
        array (
            0 => __DIR__ . '/..' . '/builderius/mustache/src',
        ),
        'Builderius\\MooMoo\\Platform\\Bundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/moomoo/plugin-platform/src/Bundle',
        ),
        'Builderius\\GraphQL\\' => 
        array (
            0 => __DIR__ . '/..' . '/webonyx/graphql-php/src',
        ),
        'Builderius\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Builderius\\DG\\ComposerCleaner\\Cleaner' => __DIR__ . '/..' . '/dg/composer-cleaner/src/ComposerCleaner/Cleaner.php',
        'Builderius\\DG\\ComposerCleaner\\Plugin' => __DIR__ . '/..' . '/dg/composer-cleaner/src/ComposerCleaner/Plugin.php',
        'Builderius\\Normalizer' => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer/Resources/stubs/Normalizer.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitfa5bbcaf1cdf95417437e5c717094074::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitfa5bbcaf1cdf95417437e5c717094074::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitfa5bbcaf1cdf95417437e5c717094074::$classMap;

        }, null, ClassLoader::class);
    }
}
