<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Builderius\\enshrined\\svgSanitize\\' => array($vendorDir . '/enshrined/svg-sanitize/src'),
    'Builderius\\Zend\\EventManager\\' => array($vendorDir . '/zendframework/zend-eventmanager/src'),
    'Builderius\\Zend\\Code\\' => array($vendorDir . '/zendframework/zend-code/src'),
    'Builderius\\Twig\\' => array($vendorDir . '/twig/twig/src'),
    'Builderius\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Builderius\\Symfony\\Polyfill\\Intl\\Normalizer\\' => array($vendorDir . '/symfony/polyfill-intl-normalizer'),
    'Builderius\\Symfony\\Polyfill\\Intl\\Grapheme\\' => array($vendorDir . '/symfony/polyfill-intl-grapheme'),
    'Builderius\\Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'Builderius\\Symfony\\Contracts\\Translation\\' => array($vendorDir . '/symfony/translation-contracts'),
    'Builderius\\Symfony\\Contracts\\Service\\' => array($vendorDir . '/symfony/service-contracts'),
    'Builderius\\Symfony\\Contracts\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher-contracts'),
    'Builderius\\Symfony\\Contracts\\Cache\\' => array($vendorDir . '/symfony/cache-contracts'),
    'Builderius\\Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Builderius\\Symfony\\Component\\VarExporter\\' => array($vendorDir . '/symfony/var-exporter'),
    'Builderius\\Symfony\\Component\\Templating\\' => array($vendorDir . '/symfony/templating'),
    'Builderius\\Symfony\\Component\\String\\' => array($vendorDir . '/symfony/string'),
    'Builderius\\Symfony\\Component\\PropertyAccess\\' => array($vendorDir . '/symfony/property-access'),
    'Builderius\\Symfony\\Component\\Inflector\\' => array($vendorDir . '/symfony/inflector'),
    'Builderius\\Symfony\\Component\\Finder\\' => array($vendorDir . '/symfony/finder'),
    'Builderius\\Symfony\\Component\\Filesystem\\' => array($vendorDir . '/symfony/filesystem'),
    'Builderius\\Symfony\\Component\\ExpressionLanguage\\' => array($vendorDir . '/symfony/expression-language'),
    'Builderius\\Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
    'Builderius\\Symfony\\Component\\DependencyInjection\\' => array($vendorDir . '/symfony/dependency-injection'),
    'Builderius\\Symfony\\Component\\Config\\' => array($vendorDir . '/symfony/config'),
    'Builderius\\Symfony\\Component\\Cache\\' => array($vendorDir . '/symfony/cache'),
    'Builderius\\Symfony\\Bridge\\Twig\\' => array($vendorDir . '/symfony/twig-bridge'),
    'Builderius\\Symfony\\Bridge\\ProxyManager\\' => array($vendorDir . '/symfony/proxy-manager-bridge'),
    'Builderius\\Sokil\\IsoCodes\\' => array($vendorDir . '/sokil/php-isocodes/src'),
    'Builderius\\Respect\\Validation\\' => array($vendorDir . '/respect/validation/library'),
    'Builderius\\Respect\\Stringifier\\' => array($vendorDir . '/respect/stringifier/src'),
    'Builderius\\Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Builderius\\Psr\\EventDispatcher\\' => array($vendorDir . '/psr/event-dispatcher/src'),
    'Builderius\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'Builderius\\Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'Builderius\\ProxyManager\\' => array($vendorDir . '/ocramius/proxy-manager/src/ProxyManager'),
    'Builderius\\PackageVersions\\' => array($vendorDir . '/ocramius/package-versions/src/PackageVersions'),
    'Builderius\\Mustache\\' => array($vendorDir . '/builderius/mustache/src'),
    'Builderius\\MooMoo\\Platform\\Bundle\\' => array($vendorDir . '/moomoo/plugin-platform/src/Bundle'),
    'Builderius\\GraphQL\\' => array($vendorDir . '/webonyx/graphql-php/src'),
    'Builderius\\' => array($baseDir . '/src'),
);
